allow for failure of pre and nightly with total success and green checkmark

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -29,6 +29,15 @@ jobs:
           arch: ${{ matrix.arch }}
       - uses: julia-actions/julia-buildpkg@latest
       - uses: julia-actions/julia-runtest@latest
+      - name: Handle optional failures and continue without failing the workflow
+        if: ${{ failure() }}
+        run: |
+          if [[ "${{ matrix.version }}" == "nightly" || "${{ matrix.version }}" == "pre" ]]; then
+            echo "::warning::Optional matrix job failed for ${{ matrix.version }}."
+            echo "optional_fail=true" >> "${GITHUB_OUTPUT}"
+            exit 0  # Ignore the error to keep the green checkmark going
+          fi
+          exit 1  # If it's not an optional job, fail the job
   build:
     runs-on: ubuntu-latest
     steps:
