handle optional failures

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -29,6 +29,18 @@ jobs:
           arch: ${{ matrix.arch }}
       - uses: julia-actions/julia-buildpkg@latest
       - uses: julia-actions/julia-runtest@latest
+
+      # Capture failure for optional jobs and continue
+      - name: Handle optional failures
+        if: ${{ failure() }}
+        run: |
+          if [[ "${{ matrix.os }}" == "nightly" || "${{ matrix.os }}" == "pre" ]]; then
+            echo "::warning::Optional matrix job failed for ${{ matrix.os }}."
+            echo "optional_fail=true" >> "${GITHUB_OUTPUT}"
+            exit 0  # Ignore the error to keep the green checkmark going
+          fi
+          exit 1  # If it's not an optional job, fail the job
+          
   build:
     runs-on: ubuntu-latest
     steps:
